# Generated by Django 3.2 on 2021-04-21 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210421_0411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attraction',
            old_name='type',
            new_name='kind',
        ),
        migrations.RenameField(
            model_name='attraction',
            old_name='name',
            new_name='title',
        ),
    ]
